/* DO NOT CHANGE ORDER OF DROP STATEMENTS */
DROP TABLE IF EXISTS Historie;
DROP TABLE IF EXISTS Follower;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Image;
DROP TABLE IF EXISTS HootMentions;
DROP TABLE IF EXISTS Reaction;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS HootTags;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Hoot;
DROP TABLE IF EXISTS HootType;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Interaction;
