@startuml
'https://plantuml.com/sequence-diagram

skinparam sequence {
    ArrowColor #444365
    ActorBorderColor #444365
    LifeLineBorderColor #444365
    LifeLineBackgroundColor #d56a4e

    ParticipantBackgroundColor #444365
    ParticipantFontName Impact
    ParticipantFontSize 17
    ParticipantFontColor #d56a4e
    ParticipantBorderColor #444365
    ParticipantBackgroundColor #444365
    ParticipantFontName Impact
    ParticipantFontSize 17
    ParticipantFontColor #d56a4e

    ActorBackgroundColor aqua
    ActorFontColor DeepSkyBlue
    ActorFontSize 17
    ActorFontName Aapex
}

skinparam collections {
    BackgroundColor #444365
    BorderColor #444365
}

skinparam entity {
    BackgroundColor #d56a4e
    BorderColor #444365
}

== Authentication ==

Client -> ":Server": << POST: login >>
activate ":Server"

":Server" --> ":Database": findUserWithLoginInformation()
":Database" --> ":Server": < User|null >

alt#Gold #LightBlue successful case
    ":Server" --> Client: JSESSIONID (Session Token)
else #Pink user not authorized
    ":Server" --> Client: << 401: Unauthorized >>
    destroy ":Server"
end

== Request Template ==

group request
    Client ->> ":Server": << METHOD: retrieve or send information >>
    activate ":Server"
    hnote over Client: showLoadingSymbol()
    ":Server" -> ":Server": mapTransferDtoToQueryData()
    ":Server" -> ":Database": sendQueryData()
    ":Database" --> ":Server": < Result QueryData >
    ":Server" -> ":Server": mapResultQueryDataToTransferDTO()
    ":Server" -->> Client: << 200: TransferDTO >>
    deactivate ":Server"
end

box Backend
    participant ":Server"
    participant ":Database"
end box

@enduml