@startuml
'https://plantuml.com/component-diagram
/'TODO: Beautify (Probably never)'/

package Frontend {
    [f.Login]
    [f.Registration]
    [f.Timeline Personal]
    [f.Timeline Full]
    [f.Timeline Search]
    [f.Any Profile Page]
    [f.My Profile Page]
    [f.Follower]
    [f.Following]
    [f.Settings]
}

[f.Login] -[hidden]down-> [f.Registration]
[f.Registration] -[hidden]down-> [f.Timeline Personal]
[f.Timeline Personal] -[hidden]down-> [f.Timeline Full]
[f.Timeline Full] -[hidden]down-> [f.Timeline Search]
[f.Timeline Search] -[hidden]down-> [f.Any Profile Page]
[f.Any Profile Page] -[hidden]down-> [f.My Profile Page]
[f.My Profile Page] -[hidden]down-> [f.Follower]
[f.Follower] -[hidden]down-> [f.Following]
[f.Following] -[hidden]down-> [f.Settings]

package Requests {
    [GetPostById]
    [GetHootsByTags]
    [GetHootsByUser]
    [GetTimelineGlobal]
    [GetTimelinePersonal]
    [GetUserData]
    [SetUserData]
    [Login]
    [Register]
    [CreatePost]
    [CreateImage]
    [CreateComment]
    [CreatePoll]

    note right of [GetTimelinePersonal]
        Only available for current User
        Id will be added via Filter
    end note
}

[GetPostById] -[hidden]down-> [GetHootsByTags]
[GetHootsByTags] -[hidden]down-> [GetHootsByUser]
[GetHootsByUser] -[hidden]down-> [GetTimelineGlobal]
[GetTimelineGlobal] -[hidden]down-> [GetTimelinePersonal]
[GetTimelinePersonal] -[hidden]down-> [GetUserData]
[GetUserData] -[hidden]down-> [SetUserData]
[SetUserData] -[hidden]down-> [Login]
[Login] -[hidden]down-> [Register]
[Register] -[hidden]down-> [CreatePost]
[CreatePost] -[hidden]down-> [CreateImage]
[CreateImage] -[hidden]down-> [CreateComment]
[CreateComment] -[hidden]down-> [CreatePoll]

package Backend {
    database "MySql" {
        [b.Hoot]
        [b.Reaction]
        [b.User]
        [b.Follower]
        [b.History]
    }
}

[b.Hoot] -[hidden]down-> [b.Reaction]
[b.Reaction] -[hidden]down-> [b.User]
[b.User] -[hidden]down-> [b.Follower]
[b.Follower] -[hidden]down-> [b.History]

Frontend -[hidden]r-> Requests
Requests -[hidden]r-> Backend


[f.Timeline Full] -r-> [GetTimelineGlobal]
[f.Timeline Personal] -r-> [GetTimelinePersonal]
[f.Timeline Full] -r-> [CreatePost]
[f.Timeline Personal] -r-> [CreatePost]
[f.My Profile Page] -r-> [CreatePost]
[f.Timeline Full] -r-> [CreateImage]
[f.Timeline Personal] -r-> [CreateImage]
[f.My Profile Page] -r-> [CreateImage]
[f.Timeline Full] -r-> [CreateComment]
[f.Timeline Personal] -r-> [CreateComment]
[f.My Profile Page] -r-> [CreateComment]
[f.Timeline Full] -r-> [CreatePoll]
[f.Timeline Personal] -r-> [CreatePoll]
[f.My Profile Page] -r-> [CreatePoll]
[f.Timeline Search] -r-> [GetHootsByTags]
[f.Any Profile Page] -r-> [GetHootsByUser]
[f.My Profile Page] -r-> [GetUserData]
[f.Login] -r-> [Login]
[f.Registration] -r-> [Register]
[f.Follower] -r-> [GetUserData]
[f.Following] -r-> [GetUserData]
[f.Settings] -r-> [SetUserData]

[Login] -r-> [b.User]
[Register] -r-> [b.User]
[GetUserData] -r-> [b.User]
[GetUserData] -r-> [b.Follower]
[GetHootsByUser] -r-> [b.Hoot]
[GetHootsByUser] -r-> [b.User]
[GetHootsByUser] -r-> [b.Reaction]
[GetTimelinePersonal] -r-> [b.Hoot]
[GetTimelinePersonal] -r-> [b.User]
[GetTimelinePersonal] -r-> [b.Reaction]
[GetTimelineGlobal] -r-> [b.Hoot]
[GetTimelineGlobal] -r-> [b.User]
[GetTimelineGlobal] -r-> [b.Reaction]
[CreatePost] -r-> [b.Hoot]
[CreateImage] -r-> [b.Hoot]
[CreateComment] -r-> [b.Hoot]
[CreatePoll] -r-> [b.Hoot]

@enduml